name: drug
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  easy_localization: ^3.0.2
  bot_toast: ^4.0.3
  fluro: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
  
  fonts:
    - family: iranYekan
      fonts:
        - asset: assets/fonts/Black.ttf
          weight: 900
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/Bold.ttf
          weight: 600
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Light.ttf
          weight: 300
        - asset: assets/fonts/Light.ttf
          weight: 200
        - asset: assets/fonts/Thin.ttf
          weight: 100
